### ISSUE TITLE
Display BiDi traffic

### ISSUE THREAD

**Issue by nchevobbe** [firefox-devtools/bidi-webconsole-prototype#10]
It would be nice to display all the BiDi packets so we could see the shape of outgoing and incoming packets without opening DevTools.
Outgoing and incoming packets would have different styles/position so we could see the "conversation".
Events packets could also be displayed differently than command results.

For displaying the packets, we could either have a dedicated "BiDi" panel (where we could have an input to send packet)
Or we could have a sidebar that could be toggled so it would be shown next to whatever panel is displayed.
This could allow us to link part of the UI to some packets, for example, clicking on a button in console message (or context menu entry) could highlight the BiDi packet it was created from

**Comment by nchevobbe** [comment]
@ochameau was also thinking that we might have link to documentation/spec on each packet, so you could see what it does

We might spawn another issue for this

**Comment by whimboo** [comment]
> @ochameau was also thinking that we might have link to documentation/spec on each packet, so you could see what it does

Good idea. Would that need browser compat data or something like that?

**Comment by juliandescottes** [comment]
Documentation set-aside (which is issue #13), the current version provides a BiDi Log tab:

<img width="677" alt="image" src="https://user-images.githubusercontent.com/1141550/213911630-41c6ebd6-a836-4b56-ab71-0c4010dd9ede.png">

We could close this one?

**Comment by lutien** [comment]
Yes, I think, we can count this one as done
