### ISSUE TITLE
what's the license?

### ISSUE THREAD

**Issue by crisdosaygo** [firefox-devtools/bidi-webconsole-prototype#30]
sorry you probably have a centralized policy somewhere for licenses on these repos, but I didn't see it, so just asking here. i'm sure you're super busy so no worries if you can't get back to this, just thanks for reading this far! :)

**Comment by juliandescottes** [comment]
Hi thanks for raising this issue! I think the license should probably be [MPL](https://www.mozilla.org/en-US/MPL/), but I'll check with the rest of the team.

**Comment by crisdosaygo** [comment]
Hey @juliandescottes you're welcome! No worries I will look out for it! :) AH, I see it is merged already haha excellent! :)
